#!/usr/bin/env bash
# Install hacash-l2-hub on a Linux VPS (systemd).
# Usage:
#   curl -fsSL ... | bash   OR
#   sudo bash scripts/install-vps.sh
#
# Env overrides:
#   PROVIDER_ID, PUBLIC_URL, FULLNODE, BOOTSTRAP, SEEDS_URL,
#   IDENTITY_PASSWORD, API_TOKEN, REGION, FEE_PPM

set -euo pipefail

PROVIDER_ID="${PROVIDER_ID:-MyHub}"
PUBLIC_URL="${PUBLIC_URL:-}"
FULLNODE="${FULLNODE:-127.0.0.1:8080}"
BOOTSTRAP="${BOOTSTRAP:-}"
SEEDS_URL="${SEEDS_URL:-}"
REGION="${REGION:-}"
FEE_PPM="${FEE_PPM:-0}"
FEE_BASE_MEI="${FEE_BASE_MEI:-0}"
BIND="${BIND:-0.0.0.0:9090}"
INSTALL_DIR="${INSTALL_DIR:-/opt/hacash-l2}"
DATA_DIR="${DATA_DIR:-/var/lib/hacash-l2}"
USER_NAME="${USER_NAME:-hacash-l2}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root: sudo bash $0"
  exit 1
fi

if [[ -z "$PUBLIC_URL" ]]; then
  # Best-effort public IP
  IP="$(curl -4 -fsS --max-time 5 ifconfig.me 2>/dev/null || true)"
  if [[ -n "$IP" ]]; then
    PUBLIC_URL="http://${IP}:9090"
    echo "PUBLIC_URL not set; using $PUBLIC_URL (prefer HTTPS + reverse proxy in production)"
  else
    echo "Set PUBLIC_URL=https://your.domain before install"
    exit 1
  fi
fi

API_TOKEN="${API_TOKEN:-$(openssl rand -hex 24 2>/dev/null || head -c 24 /dev/urandom | xxd -p)}"
IDENTITY_PASSWORD="${IDENTITY_PASSWORD:-$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p)}"

echo "==> Creating user $USER_NAME"
id "$USER_NAME" &>/dev/null || useradd --system --home "$DATA_DIR" --shell /usr/sbin/nologin "$USER_NAME"
mkdir -p "$INSTALL_DIR" "$DATA_DIR"
chown -R "$USER_NAME:$USER_NAME" "$DATA_DIR"

echo "==> Installing binary"
if [[ -x ./target/release/hacash-l2-hub ]]; then
  install -m 755 ./target/release/hacash-l2-hub /usr/local/bin/hacash-l2-hub
elif command -v hacash-l2-hub &>/dev/null; then
  echo "Using existing $(command -v hacash-l2-hub)"
else
  echo "Build first: cargo build --release"
  echo "Or copy hacash-l2-hub to /usr/local/bin/"
  exit 1
fi

ENV_FILE="/etc/hacash-l2-hub.env"
cat > "$ENV_FILE" <<EOF
# Generated by install-vps.sh — chmod 600
HACASH_L2_BIND=${BIND}
HACASH_L2_PUBLIC_URL=${PUBLIC_URL}
HACASH_L2_PROVIDER_ID=${PROVIDER_ID}
HACASH_L2_NAME=${PROVIDER_ID}
HACASH_L2_FULLNODE=${FULLNODE}
HACASH_L2_BOOTSTRAP=${BOOTSTRAP}
HACASH_L2_SEEDS_URL=${SEEDS_URL}
HACASH_L2_STATE_PATH=${DATA_DIR}/hub-state.json
HACASH_L2_API_TOKEN=${API_TOKEN}
HACASH_L2_IDENTITY_PASSWORD=${IDENTITY_PASSWORD}
HACASH_L2_ALLOW_PRIVATE_PEERS=false
HACASH_L2_PUBLIC=true
HACASH_L2_REGION=${REGION}
HACASH_L2_FEE_PPM=${FEE_PPM}
HACASH_L2_FEE_BASE_MEI=${FEE_BASE_MEI}
HACASH_L2_GOSSIP_SECS=30
HACASH_L2_WATCH_SECS=60
HACASH_L2_ANNOUNCE_ON_START=true
HACASH_L2_SIG_VERIFY=true
RUST_LOG=hacash_l2_hub=info,l2_hub=info
EOF
chmod 600 "$ENV_FILE"
chown root:root "$ENV_FILE"

UNIT="/etc/systemd/system/hacash-l2-hub.service"
cat > "$UNIT" <<'EOF'
[Unit]
Description=Hacash L2 Channel Chain hub (CSP / global mesh)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=hacash-l2
Group=hacash-l2
EnvironmentFile=/etc/hacash-l2-hub.env
ExecStart=/usr/local/bin/hacash-l2-hub
Restart=on-failure
RestartSec=5
LimitNOFILE=65535
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/hacash-l2
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable hacash-l2-hub
systemctl restart hacash-l2-hub

echo ""
echo "==> Installed"
echo "  service:  systemctl status hacash-l2-hub"
echo "  env:      $ENV_FILE  (API token + identity — keep secret)"
echo "  health:   curl -sS ${PUBLIC_URL}/health"
echo "  self:     curl -sS ${PUBLIC_URL}/v1/net/self"
echo "  discover: curl -sS ${PUBLIC_URL}/v1/discover"
echo "  provider: $PROVIDER_ID"
echo ""
echo "Save API_TOKEN and IDENTITY_PASSWORD offline. Join mesh with BOOTSTRAP/SEEDS_URL."
echo "Docs: NETWORK-GLOBAL.md"
